### ISSUE TITLE
Error on Windows7

### ISSUE THREAD

**Issue by darkoromanov** [klei/generator-klei#4]
Hi, thanks for the promising project! I have an issue when launching command:

grunt serve

I got this warning that stops the script:

Warning: Cannot read property 'main' of undefined Use --force to continue.

and this is the complete output:

PS F:\www> grunt serve
Running "serve" task

Running "clean:dist" (clean) task
Cleaning .tmp...OK

Running "clean:temp" (clean) task

Running "html2js:app" (html2js) task
Successfully converted 1 html templates to js.

Running "injector:bower" (injector) task
Missing option `template`, using `dest` as template instead
Warning: Cannot read property 'main' of undefined Use --force to continue.

Aborted due to warnings.
PS F:\www>

**Comment by joakimbeng** [comment]
Thank you!

I'll look into it!

**Comment by joakimbeng** [comment]
it seems to be a problem with an old version of bower. Am I right that your project directory does not contain a bower_components directory? If so install the latest bower version with: `npm install -g bower`, then do a new `bower install` and finally try `grunt serve` again. Does that do the trick?

**Comment by darkoromanov** [comment]
Ok, now it works but it prints about 2.3Mb of error :-\  like there was some loop. The output contains thousands and thousands of repeated errors like:

[4mRunning "watch:express_\www\bower_components,F_livereload" (watch) task[24m
Waiting...Verifying property [36mwatch.express_\www\bower_components,F_livereload.files[39m exists in config...[31mERROR[39m
[31m>> [39mUnable to process task.
[33mWarning: Required config property "watch.express_\www\bower_components,F_livereload.files" missing.[39m

and

[33mWarning: An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (An error occurred while processing a template (Maximum call stack size exceeded).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).).[39m

**Comment by joakimbeng** [comment]
Hmm, weird. Could you please post a copy of your generated Gruntfile.js, or maybe just the "express" and "watch" sections in its config? Although I think this is a problem with `grunt-express` which I'm about to exchange for `grunt-express-server` in an upcoming version anyway...

**Comment by darkoromanov** [comment]
Here are the two sections:

```
    /**
     * Server
     */
    'express': {
      options: {
        port: 1337,
        open: false,
        livereload: false,
        // change this to '0.0.0.0' to access the server from outside
        hostname: '*'
      },
      livereload: {
        options: {
          livereload: 35729,
          serverreload: true,
          showStack: true,
          server: '<%= dirs.src %>/index.js',
          bases: [
            'bower_components',
            '<%= dirs.temp %>',
            '<%= dirs.app %>',
            '<%= dirs.dist %>'
          ]
        }
      },
      dist: {
        options: {
          open: true,
          server: '<%= dirs.src %>/index.js',
          bases: [
            'bower_components',
            '<%= dirs.dist %>'
          ]
        }
      }
    },

    /**
     * Watch files and do stuff
     */
    watch: {
      base: {
        files: ['<%= dirs.api %>/**/*.js'],
        tasks: ['newer:jshint:base', 'newer:jshint:api']
      },
      styles: {
        files: ['<%= dirs.styles %>/**/*.styl', '<%= dirs.app %>/**/*.styl'],
        tasks: ['newer:stylus', 'newer:csslint', 'injector:app', 'injector:styleguide']
      },
      styleguide: {
        files: ['<%= dirs.styles %>/styleguide.html'],
        tasks: ['copy:styleguide']
      },
      templates: {
        files: ['<%= dirs.app %>/**/*.html', '!<%= dirs.app %>/<%= modulename %>.html'],
        tasks: ['html2js:app', 'injector:app']
      },
      index: {
        files: ['<%= dirs.app %>/<%= modulename %>.html'],
        tasks: ['copy:index']
      },
      app: {
        files: ['<%= dirs.app %>/**/*.js', '!<%= dirs.app %>/**/*.spec.js'],
        tasks: ['injector:app', 'newer:jshint:app']
      },
    },
```

**Comment by joakimbeng** [comment]
Hmm, I can't recreate your problem. Does it help if you reinstall all node_modules? I.e. delete the node_modules folder and rerun `npm install`... Also check if you have any old grunt-processes still lingering in the background and kill them all before you run `grunt serve` again.

**Comment by darkoromanov** [comment]
Hi, the switch to grunt-express-server won't fix the problem. The problem was instead having dots in the path of the root, that in my case was: f:\www\memo.js 

I repeated the entire installation process on f:\www\memojs and now it works.

**Comment by joakimbeng** [comment]
Did you try having dots in the folder name with `grunt-express-server` as well? I have tried it on my mac and it works, but I have no access to a windows computer at the moment to test it there..

**Comment by darkoromanov** [comment]
You're right, sorry I thought it was working because I removed the dots from the path, while I was already using your last release instead. I confirm now it works fine, thanks!

**Comment by joakimbeng** [comment]
@darkoromanov glad to hear that! Thanks!
